# Site settings
# in the templates available like {{ site.myvariable }}.
title: 化工仪表自动化
email: zhaotq@jlu.edu.cn
brand: 化工仪表自动化
headline: 吉林大学化学学院
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chemicalinstrument.github.io/" # the base hostname & protocol for your site
copyright: 吉林大学化学学院化学工程与工艺系

# Build settings
markdown: kramdown

# Contacts
email: zhaotq@jlu.edu.cn
phone: 12345678


